apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cad-gymapp
build:
  artifacts:
    #  - image: drescherflo/cad-gym-auth-service
    #    context: cad-AuthService
    #    docker: {}
    - image: drescherflo/cad-gym-frontend
      context: cad-Frontend
      docker: { }
    - image: drescherflo/cad-gym-gym-service
      context: cad-GymService
      docker: { }
    - image: drescherflo/cad-gym-user-service
      context: cad-UserService
      docker: { }
    - image: drescherflo/cad-gym-workout-service
      context: cad-WorkoutService
      docker: { }
deploy:
  kubectl:
    manifests:
      - kubernetes/frontend-configmap.yaml
      - kubernetes/frontend-deployment.yaml
      - kubernetes/frontend-service.yaml
      - kubernetes/gym-service-deployment.yaml
      - kubernetes/gym-service-service.yaml
      - kubernetes/user-service-configmap.yaml
      - kubernetes/user-service-secret.yaml
      - kubernetes/user-service-deployment.yaml
      - kubernetes/user-service-service.yaml
      - kubernetes/workout-service-configmap.yaml
      - kubernetes/workout-service-secret.yaml
      - kubernetes/workout-service-deployment.yaml
      - kubernetes/workout-service-service.yaml
      - kubernetes/ingress.yaml
