apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cad-gymapp
build:
  artifacts:
    #  - image: drescherflo/cad-gym-auth-service
    #    context: cad-AuthService
    #    docker: {}
    - image: drescherflo/cad-gym-frontend
      context: cad-Frontend
      docker: { }
    - image: drescherflo/cad-gym-gym-service
      context: cad-GymService
      docker: { }
    - image: drescherflo/cad-gym-user-service
      context: cad-UserService
      docker: { }
    - image: drescherflo/cad-gym-workout-service
      context: cad-WorkoutService
      docker: { }
deploy:
  kubectl:
    manifests:
      - cad-gymapp/templates/frontend-configmap.yaml
      - cad-gymapp/templates/frontend-deployment.yaml
      - cad-gymapp/templates/frontend-service.yaml
      - cad-gymapp/templates/gym-service-deployment.yaml
      - cad-gymapp/templates/gym-service-service.yaml
      - cad-gymapp/templates/user-service-configmap.yaml
      - cad-gymapp/templates/user-service-secret.yaml
      - cad-gymapp/templates/user-service-deployment.yaml
      - cad-gymapp/templates/user-service-service.yaml
      - cad-gymapp/templates/workout-service-configmap.yaml
      - cad-gymapp/templates/workout-service-secret.yaml
      - cad-gymapp/templates/workout-service-deployment.yaml
      - cad-gymapp/templates/workout-service-service.yaml
      - cad-gymapp/templates/invoice-cronjob-configmap.yaml
      - cad-gymapp/templates/invoice-cronjob.yaml
      - cad-gymapp/templates/ingress.yaml
