apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: {{ .Values.gatewayService.port }}
      targetPort: {{ .Values.gatewayService.port }}
