apiVersion: v1
kind: Service
metadata:
  name: gym-service-service
spec:
  type: NodePort
  selector:
    app: gym-service
  ports:
    - protocol: TCP
      port: {{ .Values.gymService.port }}
      targetPort: {{ .Values.gymService.port }}
