apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-service-deployment
  labels:
    app: gym-service
spec:
  selector:
    matchLabels:
      app: gym-service
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: gym-service
    spec:
      containers:
        - name: gym-service
          image: {{ .Values.gymService.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 7081
          resources:
            requests:
              cpu: "500m"


