apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-{{ .Values.letsencrypt.issuer }}-issuer"

spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: ssl-cert-{{ .Release.Namespace }}
  #ingressClassName: nginx
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontend.port }}
          - path: /gym
            pathType: Prefix
            backend:
              service:
                name: gym-service-service
                port:
                  number: {{ .Values.gymService.port }}
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-service-service
                port:
                  number: {{ .Values.userService.port }}
          - path: /workout
            pathType: Prefix
            backend:
              service:
                name: workout-service-service
                port:
                  number: {{ .Values.workoutService.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-service-service
                port:
                  number: {{ .Values.gatewayService.port }}
          - path: /api-docs
            pathType: Prefix
            backend:
              service:
                name: gateway-service-service
                port:
                  number: {{ .Values.gatewayService.port }}
          - path: /reporting
            pathType: Prefix
            backend:
              service:
                name: reporting-service-service
                port:
                  number: {{ .Values.reportingService.port }}

