apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-cronjob-configmap
data:
  gym_service_url: {{ .Values.gymServiceUrl }}
  user_service_url: {{ .Values.userServiceUrl }}
  cost_per_user: "{{ .Values.invoiceCronjob.costPerUser }}"
