apiVersion: batch/v1
kind: CronJob
metadata:
  name: invoice-cronjob
spec:
  schedule: '* * 1 * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-dev/cad-gym-invoice-cronjob:latest
              env:
                - name: GYM_SERVICE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: invoice-cronjob-configmap
                      key: gym_service_url
                - name: USER_SERVICE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: invoice-cronjob-configmap
                      key: user_service_url
              imagePullPolicy: Always
              name: invoice-cronjob
          restartPolicy: OnFailure
