apiVersion: batch/v1
kind: CronJob
metadata:
  name: invoice-cronjob
spec:
  schedule: "{{ .Values.invoiceCronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: {{ .Values.invoiceCronjob.image }}
              env:
                - name: GYM_SERVICE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: invoice-cronjob-configmap
                      key: gym_service_url
                - name: USER_SERVICE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: invoice-cronjob-configmap
                      key: user_service_url
                #- name: COST_PER_USER
                #  valueFrom:
                #    configMapKeyRef:
                #      name: invoice-cronjob-configmap
                #      key: cost_per_user
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              name: invoice-cronjob
          restartPolicy: {{ .Values.invoiceCronjob.restartPolicy }}
