apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-service-configmap
data:
  gym_service_url: {{ .Values.gymServiceUrl }}
  user_service_url: {{ .Values.userServiceUrl }}
  workout_service_url: {{ .Values.workoutServiceUrl }}
