apiVersion: v1
kind: Service
metadata:
  name: reporting-service-service
spec:
  selector:
    app: reporting-service
  ports:
    - protocol: TCP
      port: {{ .Values.reportingService.port }}
      targetPort: {{ .Values.reportingService.port }}
