apiVersion: v1
kind: Secret
metadata:
  name: reporting-service-secret
type: Opaque
stringData:
  gmail_smtp_username: {{ .Values.reportingService.gmailSmtpUsername }}
  gmail_smtp_password: {{ .Values.reportingService.gmailSmtpPassword }}
