apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.userService.port }}
      targetPort: {{ .Values.userService.port }}
