apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  spring_datasource_username: {{ .Values.userService.springDatasourceUsername }}
  spring_datasource_password: {{ .Values.userService.springDatasourcePassword }}
