apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service-deployment
  labels:
    app: workout-service
spec:
  selector:
    matchLabels:
      app: workout-service
  replicas: 2
  template:
    metadata:
      labels:
        app: workout-service
    spec:
      containers:
        - name: workout
          image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-dev/cad-gym-workout-service:latest
          env:
            - name: SQL_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: workout-service-configmap
                  key: sql_db_url
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: workout-service-configmap
                  key: spring_datasource_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: workout-service-secret
                  key: spring_datasource_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workout-service-secret
                  key: spring_datasource_password
          command: [ "./wait-for-it.sh" ]
          args: [ "$(SQL_DB_URL)", "--", "java", "-jar", "/WorkoutService.jar" ]
          imagePullPolicy: Always
          ports:
            - containerPort: 7083
