apiVersion: v1
kind: Service
metadata:
  name: workout-service-service
spec:
  selector:
    app: workout-service
  ports:
    - protocol: TCP
      port: {{ .Values.workoutService.port }}
      targetPort: {{ .Values.workoutService.port }}
