apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout
spec:
  selector:
    matchLabels:
      app: workout
  replicas: 1
  template:
    metadata:
      labels:
        app: workout
    spec:
      containers:
        - name: workout
          image: drescherflo/cad-gym-workout-service:dev
          ports:
            - containerPort: 7083