apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout
spec:
  selector:
    matchLabels:
      app: workout
  replicas: 1
  template:
    metadata:
      labels:
        app: workout
    spec:
      containers:
        - name: workout
          image: cad-gym-workout-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7083
          env:
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "classpath:tf_service_account_key.json"