apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym
spec:
  selector:
    matchLabels:
      app: gym
  replicas: 1
  template:
    metadata:
      labels:
        app: gym
    spec:
      containers:
        - name: gym
          image: europe-west3-docker.pkg.dev/cad-project-368216/cad-repo-dev/cad-gym-gym-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7081