apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-dev/cad-gym-frontend:latest
          env:
            - name: GYM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: gym_service_url
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: user_service_url
            - name: WORKOUT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: workout_service_url
          imagePullPolicy: Always
          ports:
            - containerPort: 80
