apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  gym_service_url: "http://gym-service-service:7081"
  user_service_url: "http://user-service-service:7082"
  workout_service_url: "http://workout-service-service:7083"
