apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  spring_datasource_username: cad  # TODO: Set user
  spring_datasource_password: test123  # TODO: Set pw and/or replace in pipeline
