autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

frontend:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-staging/cad-gym-frontend:latest

gymService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-staging/cad-gym-gym-service:latest

invoiceCronjob:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-staging/cad-gym-invoice-cronjob:latest

userService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-staging/cad-gym-user-service:latest

workoutService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-staging/cad-gym-workout-service:latest

reportingService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-staging/cad-gym-reporting-service:latest

gatewayService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-staging/cad-gym-gateway-service:latest
