domain: "premium.drescherflo.de"
letsencrypt:
  issuer: "prod"

replicas: 2

frontend:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-prod/cad-gym-frontend:latest

gymService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-prod/cad-gym-gym-service:latest

invoiceCronjob:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-prod/cad-gym-invoice-cronjob:latest

userService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-prod/cad-gym-user-service:latest

workoutService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-prod/cad-gym-workout-service:latest

reportingService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-prod/cad-gym-reporting-service:latest

gatewayService:
  image: europe-west3-docker.pkg.dev/cad-gym-app/cad-repo-prod/cad-gym-gateway-service:latest
