name: Build and Deploy

# Once a push registered to the master, dev, staging or a release branch, this workflow is executed.
# It is also executed when a pull request is merged (which leads to a push).
# Then it will run the following jobs:
# - Run terraform to create infrastructure
# - Build the docker images
# - When all builds were successful, push the new images
# - When pushing was successful, deploy the application

on:
  push:
    branches:
      - master
      - dev
      - staging
      - 'releases/**'

jobs:
  set-deployment-type:
    name: Set deployment type (dev/staging/production)
    runs-on: ubuntu-latest
    outputs:
      deployment-type: ${{ steps.set-deployment-type.outputs.type }}
    steps:
      -
        id: set-deployment-type
        run: |
          if [[ $GITHUB_REF_NAME == 'master' ]]; then
            echo "type=prod" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF_NAME == 'dev' ]]; then
            echo "type=dev" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF_NAME == 'staging' ]]; then
            echo "type=staging" >> $GITHUB_OUTPUT
          else
            #version=${$GITHUB_REF_NAME#*/}
            #echo "version=$version" >> $GITHUB_OUTPUT
            echo "type=prod" >> $GITHUB_OUTPUT
          fi

  run-terraform:
    name: Run Terraform and build infrastructure
    needs: set-deployment-type
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      -
        name: Terraform init and apply
        run: |
          export GOOGLE_CREDENTIALS='${{ secrets.GCP_KEY }}'
          DEPLOYMENT_TYPE=${{ needs.set-deployment-type.outputs.deployment-type }}
          echo $DEPLOYMENT_TYPE  # debug
          cd terraform/environments/$DEPLOYMENT_TYPE/ || exit -1
          terraform init
          terraform apply -auto-approve -input=false
      -
        name: Save repo with files generated by Terraform as tar
        run: tar -cf /tmp/repo.tar .
      -
        name: Upload repo (in tar) as artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo-with-tf-files
          path: /tmp/repo.tar

  build-and-push-docker:
    name: Build and push docker images
    needs:
      - set-deployment-type
      - run-terraform
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      server: europe-west3-docker.pkg.dev
      repo: cad-repo-${{ needs.set-deployment-type.outputs.deployment-type }}
      deployment-type: ${{ needs.set-deployment-type.outputs.deployment-type }}
    secrets:
      GCP_KEY: ${{ secrets.GCP_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  delete-repo-artifact:
    name: Delete repo artifact with Terraform files
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v2
      with:
        name: repo-with-tf-files

  deploy-application:
    name: Deploy to Google Kubernetes Engine
    needs:
      - set-deployment-type
      - build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      -
        name: Install kubectl
        run: sudo snap install kubectl --classic
      -
        name: Install helm
        run: sudo snap install helm --classic
      -
        name: Configure kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          DEPLOYMENT_TYPE=${{ needs.set-deployment-type.outputs.deployment-type }}
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials cluster-$DEPLOYMENT_TYPE --zone europe-west3-c
      -
        name: Deploy application
        run: |
          DEPLOYMENT_TYPE=${{ needs.set-deployment-type.outputs.deployment-type }}
          helm upgrade --install ingress-nginx ingress-nginx \
            --repo https://kubernetes.github.io/ingress-nginx \
            --namespace ingress-nginx --create-namespace
          
          cd helm || exit -1
          if [[ $DEPLOYMENT_TYPE == 'dev' ]]; then
            echo "Deploying to dev"
            echo "Deploying user-db"
            helm upgrade --install postgresql-user postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-user-values.yaml
            echo "Deploying workout-db"
            helm upgrade --install postgresql-workout postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-workout-values.yaml
            sleep 10  # required for ingress to fully start up
            echo "Deploying gymapp"
            helm upgrade --install gymapp cad-gymapp
          elif [[ $DEPLOYMENT_TYPE == 'staging' ]]; then
            echo "Deploying to staging"
            # Free Deployment
            echo "Deploying free"
            echo "Deploying user-db"
            helm upgrade --install postgresql-user postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-user-values.yaml \
              --namespace free --create-namespace
            echo "Deploying workout-db"
            helm upgrade --install postgresql-workout postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-workout-values.yaml \
              --namespace free --create-namespace
            sleep 10  # required for ingress to fully start up
            echo "Deploying gymapp"
            helm upgrade --install gymapp cad-gymapp \
              --values=gymapp-staging-free-deployment.yaml \
              --namespace free --create-namespace
            # Premium Deployment
            echo "Deploying premium"
            echo "Deploying user-db"
            helm upgrade --install postgresql-user postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-user-values.yaml \
              --namespace premium --create-namespace
            echo "Deploying workout-db"
            helm upgrade --install postgresql-workout postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-workout-values.yaml \
              --namespace premium --create-namespace
            echo "Deploying gymapp"
            helm upgrade --install gymapp cad-gymapp \
              --values=gymapp-staging-premium-deployment.yaml \
              --namespace premium --create-namespace
            # Enterprise Deployment:
              while read client; do
                echo "Deploying enterprise client: $client"
                echo "Deploying user-db"
                helm upgrade --install postgresql-user postgresql-ha \
                  --repo https://charts.bitnami.com/bitnami \
                  --values=postgresql-user-values.yaml \
                  --namespace enterprise-$client --create-namespace
                echo "Deploying workout-db"
                helm upgrade --install postgresql-workout postgresql-ha \
                  --repo https://charts.bitnami.com/bitnami \
                  --values=postgresql-workout-values.yaml \
                  --namespace enterprise-$client --create-namespace
                echo "Deploying gymapp"
                helm upgrade --install gymapp cad-gymapp \
                  --values=gymapp-staging-enterprise-deployment.yaml \
                  --set domain="$client.staging.drescherflo.de" \
                  --namespace enterprise-$client --create-namespace
              done < enterprise-clients.txt
          else
            echo "Deploying to prod"
            # Free Deployment
            echo "Deploying free"
            echo "Deploying user-db"
            helm upgrade --install postgresql-user postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-user-values.yaml \
              --namespace free --create-namespace
            echo "Deploying workout-db"
            helm upgrade --install postgresql-workout postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-workout-values.yaml \
              --namespace free --create-namespace
            sleep 10  # required for ingress to fully start up
            echo "Deploying gymapp"
            helm upgrade --install gymapp cad-gymapp \
              --values=gymapp-prod-free-deployment.yaml \
              --namespace free --create-namespace
            # Premium Deployment
            echo "Deploying premium"
            echo "Deploying user-db"
            helm upgrade --install postgresql-user postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-user-values.yaml \
              --namespace premium --create-namespace
            echo "Deploying workout-db"
            helm upgrade --install postgresql-workout postgresql-ha \
              --repo https://charts.bitnami.com/bitnami \
              --values=postgresql-workout-values.yaml \
              --namespace premium --create-namespace
            echo "Deploying gymapp"
            helm upgrade --install gymapp cad-gymapp \
              --values=gymapp-prod-premium-deployment.yaml \
              --namespace premium --create-namespace
            # Enterprise Deployment:
              while read client; do
                echo "Deploying enterprise client: $client"
                echo "Deploying user-db"
                helm upgrade --install postgresql-user postgresql-ha \
                  --repo https://charts.bitnami.com/bitnami \
                  --values=postgresql-user-values.yaml \
                  --namespace enterprise-$client --create-namespace
                echo "Deploying workout-db"
                helm upgrade --install postgresql-workout postgresql-ha \
                  --repo https://charts.bitnami.com/bitnami \
                  --values=postgresql-workout-values.yaml \
                  --namespace enterprise-$client --create-namespace
                echo "Deploying gymapp"
                helm upgrade --install gymapp cad-gymapp \
                  --values=gymapp-prod-enterprise-deployment.yaml \
                  --set domain="$client.drescherflo.de" \
                  --namespace enterprise-$client --create-namespace
              done < enterprise-clients.txt
          fi
