# Reusable docker build workflow
# Pushes the previously built image

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      repo:
        required: true
        type: string
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      GCP_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}
          path: /tmp
      -
        name: Delete docker image artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ inputs.tag }}
      -
        name: Setup gcloud cli
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      -
        name: Configure Docker to use gcloud
        run: |
          gcloud --quiet auth configure-docker europe-west3-docker.pkg.dev
      -
        name: Load downloaded docker image
        run: docker load --input /tmp/${{ inputs.tag }}.tar
      -
        name: Push docker image
        run: docker push ${{ inputs.server }}/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.repo }}/${{ inputs.tag }}:${{ inputs.version }}
