# Reusable docker build workflow
# Checks out the repo and builds the required docker image

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      server:
        required: true
        type: string
      repo:
        required: true
        type: string
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      GCP_PROJECT_ID:
        required: true


jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download repo with Terraform files
        uses: actions/download-artifact@v3
        with:
          name: repo-with-tf-files
          path: /tmp
      -
        name: Extract repo
        run: tar -xf /tmp/repo.tar .
      -
        name: Build docker image
        run: docker build -t ${{ inputs.server }}/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.repo }}/${{ inputs.tag }}:${{ inputs.version }} ${{ inputs.context }}
      -
        name: Save docker image in artifact
        run: docker save -o /tmp/${{ inputs.tag }}.tar ${{ inputs.server }}/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.repo }}/${{ inputs.tag }}:${{ inputs.version }}
      -
        name: Upload docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.tag }}
          path: /tmp/${{ inputs.tag }}.tar
