# Reusable docker build workflow
# Pushes the previously built image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Log in to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Download docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.tag }}
          path: /tmp
      -
        name: Load downloaded docker image
        run: docker load --input /tmp/${{ inputs.tag }}.tar
      -
        name: Push docker image
        run: docker push ${{ secrets.DOCKER_USER }}/${{ inputs.tag }}:${{ inputs.version }}
