name: Docker Build and Deploy

# Once a push registered to the master, dev or a release branch, this workflow is executed.
# It is also executed when a pull request is merged (which leads to a push).
# Then it will run the following jobs:
# - Build the docker images
# - When all builds were successful, push the new images

on:
  push:
    branches:
      - master
      - dev
      - staging
      - 'releases/**'

jobs:
  set-image-version:
    name: Set docker image tag version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-tag.outputs.version }}
    steps:
      -
        id: set-tag
        run: |
          if [[ $GITHUB_REF_NAME == 'master' ]]; then
            echo "version=latest" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF_NAME == 'dev' ]]; then
            echo "version=dev" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF_NAME == 'staging' ]]; then
            echo "version=staging" >> $GITHUB_OUTPUT
          else
            version=${$GITHUB_REF_NAME#*/}
            echo "version=$version" >> $GITHUB_OUTPUT
          fi

  build-frontend:
    name: Build Frontend
    needs: set-image-version
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./cad-Frontend
      tag: cad-gym-frontend
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}

  build-auth-service:
    name: Build AuthService
    needs: set-image-version
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./cad-AuthService
      tag: cad-gym-auth-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}

  build-gym-service:
    name: Build GymService
    needs: set-image-version
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./cad-GymService
      tag: cad-gym-gym-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}

  build-user-service:
    name: Build UserService
    needs: set-image-version
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./cad-UserService
      tag: cad-gym-user-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      
  build-workout-service:
    name: Build WorkoutService
    needs: set-image-version
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./cad-WorkoutService
      tag: cad-gym-workout-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      
  push-frontend:
    name: Push Frontend
    needs:
      - set-image-version
      - build-frontend
      - build-auth-service
      - build-gym-service
      - build-user-service
      - build-workout-service
    uses: ./.github/workflows/docker-push.yml
    with:
      tag: cad-gym-frontend
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-auth-service:
    name: Push AuthService
    needs:
      - set-image-version
      - build-frontend
      - build-auth-service
      - build-gym-service
      - build-user-service
      - build-workout-service
    uses: ./.github/workflows/docker-push.yml
    with:
      tag: cad-gym-auth-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-gym-service:
    name: Push GymService
    needs:
      - set-image-version
      - build-frontend
      - build-auth-service
      - build-gym-service
      - build-user-service
      - build-workout-service
    uses: ./.github/workflows/docker-push.yml
    with:
      tag: cad-gym-gym-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-user-service:
    name: Push UserService
    needs:
      - set-image-version
      - build-frontend
      - build-auth-service
      - build-gym-service
      - build-user-service
      - build-workout-service
    uses: ./.github/workflows/docker-push.yml
    with:
      tag: cad-gym-user-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-workout-service:
    name: Push WorkoutService
    needs:
      - set-image-version
      - build-frontend
      - build-auth-service
      - build-gym-service
      - build-user-service
      - build-workout-service
    uses: ./.github/workflows/docker-push.yml
    with:
      tag: cad-gym-workout-service
      version: ${{ needs.set-image-version.outputs.version }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
