# Reusable docker build workflow
# Checks out the repo and builds the required docker image

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      tag:
        required: true
        type: string
      version:
        required: true
        type: string


jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Build docker image
        run: docker build -t ${{ inputs.tag }}:${{ inputs.version }} -o type=docker,dest=/tmp/${{ inputs.tag }}.tar ${{ inputs.context }}
      -
        name: Upload docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.tag }}
          path: /tmp/${{ inputs.tag }}.tar
